#!/bin/sh
protected_branch="main"
# push先ブランチを判定
while read local_ref local_sha remote_ref remote_sha
do
    if [ "$remote_ref" = "refs/heads/main" ]; then
        echo "--------------------------------------------------"
        echo "ERROR: mainへの直接Pushは禁止されています。"
        echo "作業用ブランチからGitHub上でPRを作成してください。"
        echo "--------------------------------------------------"
        exit 1
    fi
done
